# Generated by Django 4.1.3 on 2022-11-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Middle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='Middle', max_length=100),
            preserve_default=False,
        ),
    ]
