# Generated by Django 4.1.3 on 2022-11-06 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_address_profile_email_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.profile')),
                ('resumeUrl', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
